name: MakeExe

on: [push]

jobs:
    build:
        runs-on: windows-latest
        steps:
          - uses: actions/setup-python@v2
            with:
              python-version: 3.8
          - uses: actions/checkout@v2
          - name: Install packages
            run:  pip install -r "pythoncode/requirements.txt"
          - name: Change into pythoncode directory
            run: cd pythoncode
          - name: Create basic spec file for FortiusANT
            run: |
              & "FortiusANT Create basic spec file.bat"
          - name: Build FortiusANT
            run: |
              & "FortiusANT CreateWindowsExecutable.bat"

