name: MakeExe

on: [push]

jobs:
    build:
        runs-on: windows-latest
        steps:
          - uses: actions/setup-python@v2
            with:
              python-version: 3.8
          - uses: actions/checkout@v2
          - name: Install packages
            run:  pip install -r "pythoncode/requirements.txt"
          - name: Show files in current dir
            run: |
              dir
              cd pythoncode
              dir
            shell: cmd
          - name: Create basic spec file for FortiusANT
            run: |
              dir
              call "FortiusANT Create basic spec file.bat"
            shell: cmd
          - name: Build FortiusANT
            run: |
              call "FortiusANT CreateWindowsExecutable.bat"
            shell: cmd

