name: MakeExe

on: [push]

jobs:
    build:
        runs-on: windows-latest
        steps:
          - uses: actions/setup-python@v2
            with:
              python-version: 3.8
          - uses: actions/checkout@v2
          - name: Show working directory content
            run: dir
          - name: Install packages
            run:  pip install -r "pythoncode/requirements.txt"
          - name: Create basic spec file for FortiusANT
            run: start "pythoncode\\FortiusANT Create basic spec file.bat"
          - name: Build FortiusANT
            run: start "pythoncode\\FortiusANT CreateWindowsExecutable.bat"

