name: MakeExe

on: [push]

jobs:
    build:
        runs-on: windows-latest
        steps:
          - uses: actions/checkout@v2

          - uses: actions/setup-python@v2
            with:
              python-version: 3.8

          - uses: actions/cache@v2
            with:
              path: ~\AppData\Local\pip\Cache
              key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
              restore-keys: |
                ${{ runner.os }}-pip-

          - name: Install packages
            if: steps.cache.outputs.cache-hit != 'true'
            run:  pip install -r "pythoncode/requirements.txt"

          - name: Show files in current dir
            run: |
              cd pythoncode
              dir
            shell: cmd

          - name: Create basic spec file for FortiusANT
            run: |
              cd pythoncode
              dir
              call "FortiusANT Create basic spec file.bat"
            shell: cmd

          - name: Build FortiusANT
            run: |
              cd pythoncode
              call "FortiusANT CreateWindowsExecutable.bat"
            shell: cmd

